version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - kafka-network

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE_KAFKA:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_LISTENER_NAMES: INSIDE
      KAFKA_LISTENER_HOSTNAME: INSIDE_KAFKA
      KAFKA_LISTENER_PORT: 9092
      KAFKA_LISTENER_INTERFACE: INSIDE_KAFKA
      KAFKA_LISTENERS: INSIDE://INSIDE_KAFKA:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: 'false'
      KAFKA_NUM_PARTITIONS: 3
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    volumes:
      - /tmp/broker-metrics
    expose:
      - "9092"
    networks:
      - kafka-net

  create_topics:
    build:
      context: ./create_topics
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

  translator:
    build:
      context: ./translator
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

  phys_jud:
    build:
      context: ./phys_jud
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

  goods_category:
    build:
      context: ./goods_category
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

  d_a_goods_categories:
    build:
      context: ./d_a_goods_categories
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

  d_g_goods_categories:
    build:
      context: ./d_g_goods_categories
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

  d_r_goods_categories:
    build:
      context: ./d_r_goods_categories
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

  d_s_services_categories:
    build:
      context: ./d_s_services_categories
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

  vacancy:
    build:
      context: ./vacancy
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge

volumes:
  kafka_data: { }
