version: '3.8'
services:
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_KRAFT_CLUSTER_ID=JAVELIN
      - KAFKA_CFG_PROCESS_ROLES=controller, broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@kafka:9091
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9090,CONTROLLER://:9091,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://KAFKA:9090,EXTERNAL://${HOSTNAME:-localhost}:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CREATE_TOPICS=category-index:1:1,category-seo:1:1,goods-category-result:1:1,goods-index:1:1,goods-seo:1:1,d-a-categories-index:1:1,d-a-categories-seo:1:1,d-a-goods-index:1:1,d-a-goods-seo:1:1,d-a-result:1:1,d-g-categories-index:1:1,d-g-categories-seo:1:1,d-g-goods-index:1:1,d-g-goods-seo:1:1,d-g-result:1:1,d-r-categories-index:1:1,d-r-categories-seo:1:1,d-r-goods-index:1:1,d-r-goods-seo:1:1,d-r-result:1:1,d-s-categories-index:1:1,d-s-categories-seo:1:1,d-s-result:1:1,d-s-services-index:1:1,d-s-services-seo:1:1,jud-index:1:1,jud-seo:1:1,phys-index:1:1,phys-jud-result:1:1,phys-seo:1:1,vacancy-index:1:1,vacancy-seo:1:1,vacancy-resume-index:1:1,vacancy-resume-seo:1:1,vacancy-result:1:1,translation:1:1,translation-res:1:1
    volumes:
      - kafka_data:/bitnami/kafka
    expose:
      - "9092"
    networks:
      - kafka-network

  translator:
    build:
      context: ./translator
    container_name: translator
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

  phys_jud:
    build:
      context: ./phys_jud
    container_name: phys_jud
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

  goods_category:
    build:
      context: ./goods_category
    container_name: goods_category
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

  d_a_goods_categories:
    build:
      context: ./d_a_goods_categories
    container_name: d_a_goods_categories
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

  d_g_goods_categories:
    build:
      context: ./d_g_goods_categories
    container_name: d_g_goods_categories
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

  d_r_goods_categories:
    build:
      context: ./d_r_goods_categories
    container_name: d_r_goods_categories
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

  d_s_services_categories:
    build:
      context: ./d_s_services_categories
    container_name: d_s_services_categories
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

  vacancy:
    build:
      context: ./vacancy
    container_name: vacancy
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - kafka-network

networks:
  kafka-network:
    driver: bridge

volumes:
  kafka_data: {}

